
{% set version = "2.9.3" %}

package:
  name: qscintilla2
  version: {{ version }}

source:
  url:  http://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-{{ version }}/QScintilla_gpl-{{ version }}.tar.gz
  md5:  3b1cdbce9ef6c28cd868bcc58219f96e

build:
  number: 1004

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python
    - pip
    - sip
    - qt
    - pyqt
  run:
    - python
    - sip
    - qt
    - pyqt

about:
  home: https://www.riverbankcomputing.com/software/qscintilla/intro
  license: GPL-3.0
  summary: "Qscintilla2 editor for Qt"
  description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
    As well as features found in standard text editing components, QScintilla includes features especially useful when editing and debugging source code. These include support for syntax styling, error indicators, code completion and call tips. The selection margin can contain markers like those used in debuggers to indicate breakpoints and the current line. Styling choices are more open than with many editors, allowing the use of proportional fonts, bold and italics, multiple foreground and background colours and multiple fonts.
  doc_url: http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html
  dev_url: https://www.riverbankcomputing.com/software/qscintilla/download

extra:
  recipe-maintainers:
    - dschreij
    - ocefpaf
