
{% set version = "2.11.2" %}

package:
  name: qscintilla2
  version: {{ version }}

source:
  url:  https://www.riverbankcomputing.com/static/Downloads/QScintilla/{{ version }}/QScintilla_gpl-{{ version }}.tar.gz
  sha256: 029bdc476a069fda2cea3cd937ba19cc7fa614fb90578caef98ed703b658f4a1

build:
  number: 6
  skip: true  # [ppc64le]
  merge_build_host: true  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl') }}            # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
  host:
    - python
    - pip
    - qt
    - pyqt
  run:
    - python
    - pyqt

test:
  imports:
    - PyQt5.Qsci

about:
  home: https://www.riverbankcomputing.com/software/qscintilla/intro
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "Qscintilla2 editor for Qt"
  description: |
    "QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
    As well as features found in standard text editing components, QScintilla
    includes features especially useful when editing and debugging source code.
    These include support for syntax styling, error indicators, code completion and call tips."
  doc_url: http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html
  dev_url: https://www.riverbankcomputing.com/software/qscintilla/download

extra:
  recipe-maintainers:
    - dschreij
    - ocefpaf
    - matthiasdiener
