
{% set version = "2.11.1" %}
{% set sha256 = "dae54d19e43dba5a3f98ac084fc0bcfa6fb713fa851f1783a01404397fd722f5" %}

package:
  name: qscintilla2
  version: {{ version }}

source:
  url:  https://www.riverbankcomputing.com/static/Downloads/QScintilla/{{ version }}/QScintilla_gpl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py27]
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python
    - pip
    - sip >=4.19
    - qt
    - pyqt
  run:
    - python
    - sip >=4.19
    - qt
    - pyqt

about:
  home: https://www.riverbankcomputing.com/software/qscintilla/intro
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Qscintilla2 editor for Qt"
  description: |
    "QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
    As well as features found in standard text editing components, QScintilla
    includes features especially useful when editing and debugging source code.
    These include support for syntax styling, error indicators, code completion and call tips."
  doc_url: http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html
  dev_url: https://www.riverbankcomputing.com/software/qscintilla/download

extra:
  recipe-maintainers:
    - dschreij
    - ocefpaf
