{% set version = "2.14.1" %}

package:
  name: qscintilla2
  version: {{ version }}

source:
  url: https://www.riverbankcomputing.com/static/Downloads/QScintilla/{{ version }}/QScintilla_src-{{ version }}.tar.gz
  sha256: dfe13c6acc9d85dfcba76ccc8061e71a223957a6c02f3c343b30a9d43a4cdd4d

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - sip                                   # [build_platform != target_platform]
    - pyqt5-sip                             # [build_platform != target_platform]
  host:
    - python
    - pip
    - qt-main
    - pyqt
    - sip
    - pyqt-builder
    - libgl-devel                            # [linux]
    - libegl-devel                           # [linux]
    - libopengl-devel                        # [linux]
    - xorg-xorgproto                         # [linux]
    - xcb-util                               # [linux]
    - xcb-util-wm                            # [linux]
    - xcb-util-keysyms                       # [linux]
    - xcb-util-image                         # [linux]
    - xcb-util-renderutil                    # [linux]
    - xorg-libx11                            # [linux]
    - xorg-libxext                           # [linux]
    - xorg-libxdamage                        # [linux]
    - xorg-libsm                             # [linux]
    - xorg-libice                            # [linux]
    - xorg-libxcomposite                     # [linux]
    - xorg-libxxf86vm                        # [linux]
    - xorg-xf86vidmodeproto                  # [linux]
  run:
    - python
    - pyqt

test:
  imports:
    - PyQt5.Qsci

about:
  home: https://www.riverbankcomputing.com/software/qscintilla/intro
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Qscintilla2 editor for Qt
  description: |
    "QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
    As well as features found in standard text editing components, QScintilla
    includes features especially useful when editing and debugging source code.
    These include support for syntax styling, error indicators, code completion and call tips."
  doc_url: http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html
  dev_url: https://www.riverbankcomputing.com/software/qscintilla/download

extra:
  recipe-maintainers:
    - dschreij
    - ocefpaf
    - matthiasdiener
    - SrNetoChan
